// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth/data/entities/local_account.dart';
import 'features/diary/data/entities/vector_diary.dart';
import 'features/reminder/data/entities/local_reminder.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8387209989021689740),
    name: 'LocalAccount',
    lastPropertyId: const obx_int.IdUid(8, 4102734331881836246),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7651191783685551095),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4800505655401967285),
        name: 'username',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5306775368572039102),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8444142867025216891),
        name: 'salt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9140948016188979973),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1374530709866844278),
        name: 'lastLoginAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1391358188374180405),
        name: 'avatarPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4102734331881836246),
        name: 'hashedPrivatePin',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1672874557235948914),
    name: 'LocalReminder',
    lastPropertyId: const obx_int.IdUid(11, 8715231777229702110),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2551175573278444858),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3084510366033723997),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7437584395128343164),
        name: 'diaryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 434271976669366204),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8211127878340036937),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5954630141555527682),
        name: 'triggerAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6557925892616308834),
        name: 'repeatRule',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5726619411539027155),
        name: 'timezone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1114222100931515827),
        name: 'isEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7948132776375586498),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8715231777229702110),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4824835630835980189),
    name: 'VectorDiary',
    lastPropertyId: const obx_int.IdUid(9, 7042085998957608069),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8380703313951790088),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1638055139379730927),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1828475112365076525),
        name: 'rawText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5684995069897707780),
        name: 'aiSummary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6460992397292974401),
        name: 'aiTags',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9065914301272196941),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 8063833302195115438),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4430047299906514391),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4367878058869685764),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7042085998957608069),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 4824835630835980189),
    lastIndexId: const obx_int.IdUid(2, 8063833302195115438),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [4311661093606891552],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LocalAccount: obx_int.EntityDefinition<LocalAccount>(
      model: _entities[0],
      toOneRelations: (LocalAccount object) => [],
      toManyRelations: (LocalAccount object) => {},
      getId: (LocalAccount object) => object.id,
      setId: (LocalAccount object, int id) {
        object.id = id;
      },
      objectToFB: (LocalAccount object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        final saltOffset = object.salt == null
            ? null
            : fbb.writeString(object.salt!);
        final avatarPathOffset = object.avatarPath == null
            ? null
            : fbb.writeString(object.avatarPath!);
        final hashedPrivatePinOffset = object.hashedPrivatePin == null
            ? null
            : fbb.writeString(object.hashedPrivatePin!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, usernameOffset);
        fbb.addOffset(3, saltOffset);
        fbb.addInt64(4, object.createdAt);
        fbb.addInt64(5, object.lastLoginAt);
        fbb.addOffset(6, avatarPathOffset);
        fbb.addOffset(7, hashedPrivatePinOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final avatarPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final hashedPrivatePinParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final saltParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final lastLoginAtParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = LocalAccount(
          id: idParam,
          username: usernameParam,
          avatarPath: avatarPathParam,
          hashedPrivatePin: hashedPrivatePinParam,
          salt: saltParam,
          createdAt: createdAtParam,
          lastLoginAt: lastLoginAtParam,
        );

        return object;
      },
    ),
    LocalReminder: obx_int.EntityDefinition<LocalReminder>(
      model: _entities[1],
      toOneRelations: (LocalReminder object) => [],
      toManyRelations: (LocalReminder object) => {},
      getId: (LocalReminder object) => object.id,
      setId: (LocalReminder object, int id) {
        object.id = id;
      },
      objectToFB: (LocalReminder object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = object.body == null
            ? null
            : fbb.writeString(object.body!);
        final repeatRuleOffset = object.repeatRule == null
            ? null
            : fbb.writeString(object.repeatRule!);
        final timezoneOffset = object.timezone == null
            ? null
            : fbb.writeString(object.timezone!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.accountId);
        fbb.addInt64(2, object.diaryId);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, bodyOffset);
        fbb.addInt64(5, object.triggerAt);
        fbb.addOffset(6, repeatRuleOffset);
        fbb.addOffset(7, timezoneOffset);
        fbb.addBool(8, object.isEnabled);
        fbb.addInt64(9, object.createdAt);
        fbb.addInt64(10, object.updatedAt);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final accountIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final diaryIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final triggerAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final repeatRuleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final timezoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final isEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = LocalReminder(
          id: idParam,
          accountId: accountIdParam,
          diaryId: diaryIdParam,
          title: titleParam,
          body: bodyParam,
          triggerAt: triggerAtParam,
          repeatRule: repeatRuleParam,
          timezone: timezoneParam,
          isEnabled: isEnabledParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    VectorDiary: obx_int.EntityDefinition<VectorDiary>(
      model: _entities[2],
      toOneRelations: (VectorDiary object) => [],
      toManyRelations: (VectorDiary object) => {},
      getId: (VectorDiary object) => object.id,
      setId: (VectorDiary object, int id) {
        object.id = id;
      },
      objectToFB: (VectorDiary object, fb.Builder fbb) {
        final rawTextOffset = fbb.writeString(object.rawText);
        final aiSummaryOffset = object.aiSummary == null
            ? null
            : fbb.writeString(object.aiSummary!);
        final aiTagsOffset = object.aiTags == null
            ? null
            : fbb.writeString(object.aiTags!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.accountId);
        fbb.addOffset(2, rawTextOffset);
        fbb.addOffset(3, aiSummaryOffset);
        fbb.addOffset(4, aiTagsOffset);
        fbb.addOffset(5, embeddingOffset);
        fbb.addInt64(6, object.createdAt);
        fbb.addInt64(7, object.updatedAt);
        fbb.addBool(8, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final accountIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final rawTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final aiSummaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final aiTagsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final embeddingParam = const obx_int.Float32ListReader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = VectorDiary(
          id: idParam,
          accountId: accountIdParam,
          rawText: rawTextParam,
          aiSummary: aiSummaryParam,
          aiTags: aiTagsParam,
          embedding: embeddingParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LocalAccount] entity fields to define ObjectBox queries.
class LocalAccount_ {
  /// See [LocalAccount.id].
  static final id = obx.QueryIntegerProperty<LocalAccount>(
    _entities[0].properties[0],
  );

  /// See [LocalAccount.username].
  static final username = obx.QueryStringProperty<LocalAccount>(
    _entities[0].properties[1],
  );

  /// See [LocalAccount.salt].
  static final salt = obx.QueryStringProperty<LocalAccount>(
    _entities[0].properties[2],
  );

  /// See [LocalAccount.createdAt].
  static final createdAt = obx.QueryIntegerProperty<LocalAccount>(
    _entities[0].properties[3],
  );

  /// See [LocalAccount.lastLoginAt].
  static final lastLoginAt = obx.QueryIntegerProperty<LocalAccount>(
    _entities[0].properties[4],
  );

  /// See [LocalAccount.avatarPath].
  static final avatarPath = obx.QueryStringProperty<LocalAccount>(
    _entities[0].properties[5],
  );

  /// See [LocalAccount.hashedPrivatePin].
  static final hashedPrivatePin = obx.QueryStringProperty<LocalAccount>(
    _entities[0].properties[6],
  );
}

/// [LocalReminder] entity fields to define ObjectBox queries.
class LocalReminder_ {
  /// See [LocalReminder.id].
  static final id = obx.QueryIntegerProperty<LocalReminder>(
    _entities[1].properties[0],
  );

  /// See [LocalReminder.accountId].
  static final accountId = obx.QueryIntegerProperty<LocalReminder>(
    _entities[1].properties[1],
  );

  /// See [LocalReminder.diaryId].
  static final diaryId = obx.QueryIntegerProperty<LocalReminder>(
    _entities[1].properties[2],
  );

  /// See [LocalReminder.title].
  static final title = obx.QueryStringProperty<LocalReminder>(
    _entities[1].properties[3],
  );

  /// See [LocalReminder.body].
  static final body = obx.QueryStringProperty<LocalReminder>(
    _entities[1].properties[4],
  );

  /// See [LocalReminder.triggerAt].
  static final triggerAt = obx.QueryIntegerProperty<LocalReminder>(
    _entities[1].properties[5],
  );

  /// See [LocalReminder.repeatRule].
  static final repeatRule = obx.QueryStringProperty<LocalReminder>(
    _entities[1].properties[6],
  );

  /// See [LocalReminder.timezone].
  static final timezone = obx.QueryStringProperty<LocalReminder>(
    _entities[1].properties[7],
  );

  /// See [LocalReminder.isEnabled].
  static final isEnabled = obx.QueryBooleanProperty<LocalReminder>(
    _entities[1].properties[8],
  );

  /// See [LocalReminder.createdAt].
  static final createdAt = obx.QueryIntegerProperty<LocalReminder>(
    _entities[1].properties[9],
  );

  /// See [LocalReminder.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<LocalReminder>(
    _entities[1].properties[10],
  );
}

/// [VectorDiary] entity fields to define ObjectBox queries.
class VectorDiary_ {
  /// See [VectorDiary.id].
  static final id = obx.QueryIntegerProperty<VectorDiary>(
    _entities[2].properties[0],
  );

  /// See [VectorDiary.accountId].
  static final accountId = obx.QueryIntegerProperty<VectorDiary>(
    _entities[2].properties[1],
  );

  /// See [VectorDiary.rawText].
  static final rawText = obx.QueryStringProperty<VectorDiary>(
    _entities[2].properties[2],
  );

  /// See [VectorDiary.aiSummary].
  static final aiSummary = obx.QueryStringProperty<VectorDiary>(
    _entities[2].properties[3],
  );

  /// See [VectorDiary.aiTags].
  static final aiTags = obx.QueryStringProperty<VectorDiary>(
    _entities[2].properties[4],
  );

  /// See [VectorDiary.embedding].
  static final embedding = obx.QueryHnswProperty<VectorDiary>(
    _entities[2].properties[5],
  );

  /// See [VectorDiary.createdAt].
  static final createdAt = obx.QueryIntegerProperty<VectorDiary>(
    _entities[2].properties[6],
  );

  /// See [VectorDiary.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<VectorDiary>(
    _entities[2].properties[7],
  );

  /// See [VectorDiary.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<VectorDiary>(
    _entities[2].properties[8],
  );
}
